export const languageOptions = [
  {
    id: 45,
    name: "Assembly (NASM 2.14.02)",
    is_archived: false,
    value: "asm",
    label: "Assembly (NASM 2.14.02)",
  },
  {
    id: 2,
    name: "Bash (4.0)",
    is_archived: true,
    value: "shell",
    label: "Bash (4.0)",
  },
  {
    id: 1,
    name: "Bash (4.4)",
    is_archived: true,
    value: "shell",
    label: "Bash (4.4)",
  },
  {
    id: 46,
    name: "Bash (5.0.0)",
    is_archived: false,
    value: "shell",
    label: "Bash (5.0.0)",
  },
  {
    id: 3,
    name: "Basic (fbc 1.05.0)",
    is_archived: true,
    value: "basic",
    label: "Basic (fbc 1.05.0)",
  },
  {
    id: 47,
    name: "Basic (FBC 1.07.1)",
    is_archived: false,
    value: "basic",
    label: "Basic (FBC 1.07.1)",
  },
  {
    id: 15,
    name: "C++ (g++ 4.8.5)",
    is_archived: true,
    value: "cpp",
    label: "C++ (g++ 4.8.5)",
  },
  {
    id: 14,
    name: "C++ (g++ 4.9.4)",
    is_archived: true,
    value: "cpp",
    label: "C++ (g++ 4.9.4)",
  },
  {
    id: 13,
    name: "C++ (g++ 5.4.0)",
    is_archived: true,
    value: "cpp",
    label: "C++ (g++ 5.4.0)",
  },
  {
    id: 12,
    name: "C++ (g++ 6.3.0)",
    is_archived: true,
    value: "cpp",
    label: "C++ (g++ 6.3.0)",
  },
  {
    id: 11,
    name: "C++ (g++ 6.4.0)",
    is_archived: true,
    value: "cpp",
    label: "C++ (g++ 6.4.0)",
  },
  {
    id: 10,
    name: "C++ (g++ 7.2.0)",
    is_archived: true,
    value: "cpp",
    label: "C++ (g++ 7.2.0)",
  },
  {
    id: 9,
    name: "C (gcc 4.8.5)",
    is_archived: true,
    value: "c",
    label: "C (gcc 4.8.5)",
  },
  {
    id: 8,
    name: "C (gcc 4.9.4)",
    is_archived: true,
    value: "c",
    label: "C (gcc 4.9.4)",
  },
  {
    id: 7,
    name: "C (gcc 5.4.0)",
    is_archived: true,
    value: "c",
    label: "C (gcc 5.4.0)",
  },
  {
    id: 6,
    name: "C (gcc 6.3.0)",
    is_archived: true,
    value: "c",
    label: "C (gcc 6.3.0)",
  },
  {
    id: 5,
    name: "C (gcc 6.4.0)",
    is_archived: true,
    value: "c",
    label: "C (gcc 6.4.0)",
  },
  {
    id: 4,
    name: "C (gcc 7.2.0)",
    is_archived: true,
    value: "c",
    label: "C (gcc 7.2.0)",
  },
  {
    id: 48,
    name: "C (GCC 7.4.0)",
    is_archived: false,
    value: "c",
    label: "C (GCC 7.4.0)",
  },
  {
    id: 52,
    name: "C++ (GCC 7.4.0)",
    is_archived: false,
    value: "cpp",
    label: "C++ (GCC 7.4.0)",
  },
  {
    id: 49,
    name: "C (GCC 8.3.0)",
    is_archived: false,
    value: "c",
    label: "C (GCC 8.3.0)",
  },
  {
    id: 53,
    name: "C++ (GCC 8.3.0)",
    is_archived: false,
    value: "cpp",
    label: "C++ (GCC 8.3.0)",
  },
  {
    id: 50,
    name: "C (GCC 9.2.0)",
    is_archived: false,
    value: "c",
    label: "C (GCC 9.2.0)",
  },
  {
    id: 54,
    name: "C++ (GCC 9.2.0)",
    is_archived: false,
    value: "cpp",
    label: "C++ (GCC 9.2.0)",
  },
  {
    id: 18,
    name: "Clojure (1.8.0)",
    is_archived: true,
    value: "clojure",
    label: "Clojure (1.8.0)",
  },
  {
    id: 17,
    name: "C# (mono 5.2.0.224)",
    is_archived: true,
    value: "csharp",
    label: "C# (mono 5.2.0.224)",
  },
  {
    id: 16,
    name: "C# (mono 5.4.0.167)",
    is_archived: true,
    value: "csharp",
    label: "C# (mono 5.4.0.167)",
  },
  {
    id: 51,
    name: "C# (Mono 6.6.0.161)",
    is_archived: false,
    value: "csharp",
    label: "C# (Mono 6.6.0.161)",
  },
  {
    id: 55,
    name: "Common Lisp (SBCL 2.0.0)",
    is_archived: false,
    value: "lisp",
    label: "Common Lisp (SBCL 2.0.0)",
  },
  {
    id: 19,
    name: "Crystal (0.23.1)",
    is_archived: true,
    value: "crystal",
    label: "Crystal (0.23.1)",
  },
  {
    id: 56,
    name: "D (DMD 2.089.1)",
    is_archived: false,
    value: "d",
    label: "D (DMD 2.089.1)",
  },
  {
    id: 20,
    name: "Elixir (1.5.1)",
    is_archived: true,
    value: "elixir",
    label: "Elixir (1.5.1)",
  },
  {
    id: 57,
    name: "Elixir (1.9.4)",
    is_archived: false,
    value: "elixir",
    label: "Elixir (1.9.4)",
  },
  {
    id: 21,
    name: "Erlang (OTP 20.0)",
    is_archived: true,
    value: "erlang",
    label: "Erlang (OTP 20.0)",
  },
  {
    id: 58,
    name: "Erlang (OTP 22.2)",
    is_archived: false,
    value: "erlang",
    label: "Erlang (OTP 22.2)",
  },
  {
    id: 22,
    name: "Go (1.10.2)",
    is_archived: true,
    value: "go",
    label: "Go (1.10.2)",
  },
  {
    id: 59,
    name: "Go (1.15.5)",
    is_archived: false,
    value: "go",
    label: "Go (1.15.5)",
  },
  {
    id: 23,
    name: "Haskell (GHC 8.0.2)",
    is_archived: true,
    value: "haskell",
    label: "Haskell (GHC 8.0.2)",
  },
  {
    id: 60,
    name: "Haskell (GHC 8.10.4)",
    is_archived: false,
    value: "haskell",
    label: "Haskell (GHC 8.10.4)",
  },
  {
    id: 24,
    name: "Java (OpenJDK 8)",
    is_archived: true,
    value: "java",
    label: "Java (OpenJDK 8)",
  },
  {
    id: 61,
    name: "Java (OpenJDK 14)",
    is_archived: false,
    value: "java",
    label: "Java (OpenJDK 14)",
  },
  {
    id: 25,
    name: "JavaScript (nodejs 6.11.1)",
    is_archived: true,
    value: "javascript",
    label: "JavaScript (nodejs 6.11.1)",
  },
  {
    id: 62,
    name: "JavaScript (nodejs 16.13.0)",
    is_archived: false,
    value: "javascript",
    label: "JavaScript (nodejs 16.13.0)",
  },
  {
    id: 26,
    name: "Julia (1.0.0)",
    is_archived: true,
    value: "julia",
    label: "Julia (1.0.0)",
  },
  {
    id: 63,
    name: "Julia (1.8.0)",
    is_archived: false,
    value: "julia",
    label: "Julia (1.8.0)",
  },
  {
    id: 27,
    name: "Kotlin (1.3.50)",
    is_archived: true,
    value: "kotlin",
    label: "Kotlin (1.3.50)",
  },
  {
    id: 64,
    name: "Lua (5.3.5)",
    is_archived: false,
    value: "lua",
    label: "Lua (5.3.5)",
  },
  {
    id: 28,
    name: "OCaml (4.05.0)",
    is_archived: true,
    value: "ocaml",
    label: "OCaml (4.05.0)",
  },
  {
    id: 65,
    name: "OCaml (4.09.0)",
    is_archived: false,
    value: "ocaml",
    label: "OCaml (4.09.0)",
  },
  {
    id: 29,
    name: "Octave (4.2.0)",
    is_archived: true,
    value: "octave",
    label: "Octave (4.2.0)",
  },
  {
    id: 66,
    name: "Octave (5.1.0)",
    is_archived: false,
    value: "octave",
    label: "Octave (5.1.0)",
  },
  {
    id: 30,
    name: "Pascal (fpc 3.0.0)",
    is_archived: true,
    value: "pascal",
    label: "Pascal (fpc 3.0.0)",
  },
  {
    id: 67,
    name: "Pascal (FPC 3.0.4)",
    is_archived: false,
    value: "pascal",
    label: "Pascal (FPC 3.0.4)",
  },
  {
    id: 31,
    name: "PHP (7.4.1)",
    is_archived: true,
    value: "php",
    label: "PHP (7.4.1)",
  },
  {
    id: 68,
    name: "Plain Text",
    is_archived: false,
    value: "plaintext",
    label: "Plain Text",
  },
  {
    id: 32,
    name: "Prolog (GNU Prolog 1.4.5)",
    is_archived: true,
    value: "prolog",
    label: "Prolog (GNU Prolog 1.4.5)",
  },
  {
    id: 69,
    name: "Python (2.7.9)",
    is_archived: false,
    value: "python",
    label: "Python (2.7.9)",
  },
  {
    id: 33,
    name: "Python (3.6.0)",
    is_archived: true,
    value: "python",
    label: "Python (3.6.0)",
  },
  {
    id: 70,
    name: "Python (3.5.3)",
    is_archived: false,
    value: "python",
    label: "Python (3.5.3)",
  },
  {
    id: 34,
    name: "Python (2.6.9)",
    is_archived: true,
    value: "python",
    label: "Python (2.6.9)",
  },
  {
    id: 71,
    name: "Python (2.7.17)",
    is_archived: false,
    value: "python",
    label: "Python (2.7.17)",
  },
  {
    id: 35,
    name: "Ruby (2.7.0)",
    is_archived: true,
    value: "ruby",
    label: "Ruby (2.7.0)",
  },
  {
    id: 72,
    name: "Rust (1.40.0)",
    is_archived: false,
    value: "rust",
    label: "Rust (1.40.0)",
  },
  {
    id: 36,
    name: "TypeScript (3.7.4)",
    is_archived: true,
    value: "typescript",
    label: "TypeScript (3.7.4)",
  },
];
